site_name: 技术传播百态说
theme:
  name: material
  language: zh
  logo: assets/logo/logo_v3.svg
  favicon: assets/logo/favicon.ico
  palette:
    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: custom
      accent: custom
    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: custom
      accent: custom
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.path
    - toc.follow
  custom_dir: overrides

extra_css:
  - stylesheets/palette.css
  - stylesheets/page.css
  - stylesheets/nav.css
  - stylesheets/header.css
  - stylesheets/footer.css

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.bootcdn.net/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js

extra:
  homepage: https://www.tcblabber.cn/
  doc_title: "轻松入门电机学"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wongyah
      name: "轻松入门电机学"
    - icon: simple/wechat
      link: "https://mp.weixin.qq.com/s?__biz=MzA5NzU4ODAwOQ==&mid=2247487464&idx=1&sn=c57c1b993dcb2c166d88bc2c0d414a10&chksm=909fc9aea7e840b874ebe3e37d0e2a58de7c4c4c5e18f1355b1a4be6378b5752c571c4aeddd4&token=587590048&lang=zh_CN#rd"
      name: "微信公众号@技术传播百态说"
    - icon: simple/zhihu
      link: "https://www.zhihu.com/column/c_1317038155468161024"
      name: "知乎专栏@工控之星"
    - icon: material/email
      link: "mailto:wongyah@126.com?subject=Markdown%20Syntax%20Hub"
      name: "我的邮箱"

copyright: "&copy; 2025 王烨."

nav:
  - 机械原理基础:
    - machinery-principles/index.md
    - 定轴转动:
      - machinery-principles/rotational-motion/what-is-rotational-motion.md
      - machinery-principles/rotational-motion/newtons-law-of-rotation.md
      - machinery-principles/rotational-motion/work-and-power-of-rotation-motion.md
    - 磁场:
      - machinery-principles/magnetic-field/amperes-law.md
      - machinery-principles/magnetic-field/ohms-law-in-magnetic-circuit.md
      - machinery-principles/magnetic-field/examples.md
      - machinery-principles/magnetic-field/magnetization-curve.md
      - machinery-principles/magnetic-field/hysteresis-loop.md
      - machinery-principles/magnetic-field/faradays-law.md
      - machinery-principles/magnetic-field/induced-force.md
      - machinery-principles/magnetic-field/induced-voltage.md
      - machinery-principles/magnetic-field/linear-dc-machine.md
      - machinery-principles/magnetic-field/linear-dc-motor.md

markdown_extensions:
  - nl2br
  - abbr
  - footnotes
  - def_list
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      linenums: true
      auto_title: true
  - pymdownx.snippets:
      base_path: snippets
  - pymdownx.arithmatex:
      generic: true

